//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.StaffRegisterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StaffRegisterService.ISignUpService")]
    public interface ISignUpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignUpService/signUp", ReplyAction="http://tempuri.org/ISignUpService/signUpResponse")]
        string signUp(string name, string username, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignUpService/signUp", ReplyAction="http://tempuri.org/ISignUpService/signUpResponse")]
        System.Threading.Tasks.Task<string> signUpAsync(string name, string username, string password, string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignUpServiceChannel : WebApp.StaffRegisterService.ISignUpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignUpServiceClient : System.ServiceModel.ClientBase<WebApp.StaffRegisterService.ISignUpService>, WebApp.StaffRegisterService.ISignUpService {
        
        public SignUpServiceClient() {
        }
        
        public SignUpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignUpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string signUp(string name, string username, string password, string role) {
            return base.Channel.signUp(name, username, password, role);
        }
        
        public System.Threading.Tasks.Task<string> signUpAsync(string name, string username, string password, string role) {
            return base.Channel.signUpAsync(name, username, password, role);
        }
    }
}
