//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.PaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/MakePayment", ReplyAction="http://tempuri.org/IPaymentService/MakePaymentResponse")]
        string MakePayment(string username, int cardNo, int cvv, int expmonth, int expyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/MakePayment", ReplyAction="http://tempuri.org/IPaymentService/MakePaymentResponse")]
        System.Threading.Tasks.Task<string> MakePaymentAsync(string username, int cardNo, int cvv, int expmonth, int expyear);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : WebApp.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<WebApp.PaymentService.IPaymentService>, WebApp.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MakePayment(string username, int cardNo, int cvv, int expmonth, int expyear) {
            return base.Channel.MakePayment(username, cardNo, cvv, expmonth, expyear);
        }
        
        public System.Threading.Tasks.Task<string> MakePaymentAsync(string username, int cardNo, int cvv, int expmonth, int expyear) {
            return base.Channel.MakePaymentAsync(username, cardNo, cvv, expmonth, expyear);
        }
    }
}
